apiVersion: v1
kind: List
items:
  - metadata:
      labels:
        name: weave-net
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-c1f3803",
            "original-request": {
              "url": "/k8s/v1.5/net?v=latest",
              "date": "Tue Apr 18 2017 14:59:54 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    apiVersion: v1
    kind: ServiceAccount
  - metadata:
      labels:
        name: weave-net
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-c1f3803",
            "original-request": {
              "url": "/k8s/v1.5/net?v=latest",
              "date": "Tue Apr 18 2017 14:59:54 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            name: weave-net
          annotations:
            scheduler.alpha.kubernetes.io/tolerations: >-
              [{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]
        spec:
          containers:
            - name: weave
              image: 'weaveworks/weave-kube:latest'
              imagePullPolicy: Always
              command:
                - /home/weave/launch.sh
              env: []
              livenessProbe:
                initialDelaySeconds: 30
                httpGet:
                  host: 127.0.0.1
                  path: /status
                  port: 6784
              volumeMounts:
                - name: weavedb
                  mountPath: /weavedb
                - name: cni-bin
                  mountPath: /host/opt
                - name: cni-bin2
                  mountPath: /host/home
                - name: cni-conf
                  mountPath: /host/etc
                - name: dbus
                  mountPath: /host/var/lib/dbus
                - name: lib-modules
                  mountPath: /lib/modules
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
            - name: weave-npc
              image: 'weaveworks/weave-npc:latest'
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
          volumes:
            - name: weavedb
              emptyDir: {}
            - name: cni-bin
              hostPath:
                path: /opt
            - name: cni-bin2
              hostPath:
                path: /home
            - name: cni-conf
              hostPath:
                path: /etc
            - name: dbus
              hostPath:
                path: /var/lib/dbus
            - name: lib-modules
              hostPath:
                path: /lib/modules
          hostPID: true
          hostNetwork: true
          serviceAccountName: weave-net
          restartPolicy: Always
          securityContext:
            seLinuxOptions:
              type: spc_t
    apiVersion: extensions/v1beta1
    kind: DaemonSet
